In [1]:
import pandas as pd
import random
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

### 訓練資料比數共有 32975653 筆 (50萬名客戶與24天的交易紀錄)

In [3]:
FILE_NAME = './2021玉山人工智慧公開挑戰賽冬季賽訓練資料集.gz/tbrain_cc_training_48tags_hash_final.csv'

# N = sum(1 for line in open(FILE_NAME)) - 1 
# number of records in file (excludes header)
N = 32975653
SAMPLE_SIZE = N // 5

# Loading sample size of dataset 
skip = np.sort(np.random.choice(np.arange(1, N+1), N-SAMPLE_SIZE, replace=False))
df = pd.read_csv(FILE_NAME, skiprows=skip)
df.tail(10)

,dt,chid,shop_tag,txn_cnt,txn_amt,domestic_offline_cnt,domestic_online_cnt,overseas_offline_cnt,overseas_online_cnt,domestic_offline_amt_pct,domestic_online_amt_pct,overseas_offline_amt_pct,overseas_online_amt_pct,card_1_txn_cnt,card_2_txn_cnt,card_3_txn_cnt,card_4_txn_cnt,card_5_txn_cnt,card_6_txn_cnt,card_7_txn_cnt,card_8_txn_cnt,card_9_txn_cnt,card_10_txn_cnt,card_11_txn_cnt,card_12_txn_cnt,card_13_txn_cnt,card_14_txn_cnt,card_other_txn_cnt,card_1_txn_amt_pct,card_2_txn_amt_pct,card_3_txn_amt_pct,card_4_txn_amt_pct,card_5_txn_amt_pct,card_6_txn_amt_pct,card_7_txn_amt_pct,card_8_txn_amt_pct,card_9_txn_amt_pct,card_10_txn_amt_pct,card_11_txn_amt_pct,card_12_txn_amt_pct,card_13_txn_amt_pct,card_14_txn_amt_pct,card_other_txn_amt_pct,masts,educd,trdtp,naty,poscd,cuorg,slam,gender_code,age,primary_card
6595120,24,10193103,35,1,4451.143591,0,1,0,0,0.0,1.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,3.0,8.0,1,2,30,82203.126286,0.0,3.0,1
6595121,24,10281548,19,1,7320.353212,0,1,0,0,0.0,1.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,4.0,11.0,1,2,30,102382.569589,0.0,4.0,1
6595122,24,10380924,37,2,9627.458307,0,2,0,0,0.0,1.0,0.0,0.0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,3.0,12.0,1,3,30,111772.655354,0.0,4.0,1
6595123,24,10281548,21,1,2791.357748,0,1,0,0,0.0,1.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,4.0,11.0,1,2,30,102382.569589,0.0,4.0,1
6595124,24,10281548,37,7,3918.914112,0,7,0,0,0.0,1.0,0.0,0.0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,4.0,11.0,1,2,30,102382.569589,0.0,4.0,1
6595125,24,10164946,15,1,6283.163302,1,0,0,0,1.0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,3.0,15.0,1,99,30,38072.451849,0.0,3.0,1
6595126,24,10164946,45,1,1969.038770,1,0,0,0,1.0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,3.0,15.0,1,99,30,38072.451849,0.0,3.0,1
6595127,24,10057828,37,2,13540.095270,0,2,0,0,0.0,1.0,0.0,0.0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,6.0,15.0,1,99,30,65680.229561,0.0,6.0,0
6595128,24,10297394,16,1,7741.144057,1,0,0,0,1.0,0.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,3.0,15.0,1,2,30,59701.507360,0.0,2.0,1
6595129,24,10062431,10,1,6257.629931,0,0,0,1,0.0,0.0,0.0,1.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,6.0,15.0,1,2,30,62730.806297,0.0,2.0,1

### txn_cnt 消費次數<= 0 但有消費佔比 (card_txt_amt_pct)

In [4]:
df[df['txn_cnt'] <= 0].describe()

,dt,chid,txn_cnt,txn_amt,domestic_offline_cnt,domestic_online_cnt,overseas_offline_cnt,overseas_online_cnt,domestic_offline_amt_pct,domestic_online_amt_pct,overseas_offline_amt_pct,overseas_online_amt_pct,card_1_txn_cnt,card_2_txn_cnt,card_3_txn_cnt,card_4_txn_cnt,card_5_txn_cnt,card_6_txn_cnt,card_7_txn_cnt,card_8_txn_cnt,card_9_txn_cnt,card_10_txn_cnt,card_11_txn_cnt,card_12_txn_cnt,card_13_txn_cnt,card_14_txn_cnt,card_other_txn_cnt,card_1_txn_amt_pct,card_2_txn_amt_pct,card_3_txn_amt_pct,card_4_txn_amt_pct,card_5_txn_amt_pct,card_6_txn_amt_pct,card_7_txn_amt_pct,card_8_txn_amt_pct,card_9_txn_amt_pct,card_10_txn_amt_pct,card_11_txn_amt_pct,card_12_txn_amt_pct,card_13_txn_amt_pct,card_14_txn_amt_pct,card_other_txn_amt_pct,masts,educd,trdtp,naty,poscd,cuorg,slam,gender_code,age,primary_card
count,15610.000000,1.561000e+04,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.00000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,15610.000000,1.470900e+04,15439.000000,15439.000000,15610.000000
mean,13.314798,1.025008e+07,-0.086675,8338.759290,-0.009353,-0.043562,-0.003395,-0.030365,0.329233,0.559070,0.013728,0.09797,-0.018258,-0.014350,-0.003331,-0.012108,-0.003523,-0.017104,-0.001730,-0.001025,-0.001345,-0.002306,-0.001025,-0.000897,-0.001602,-0.000064,-0.008008,0.204299,0.174717,0.037912,0.165847,0.026586,0.183099,0.016074,0.022132,0.019014,0.025507,0.009434,0.012903,0.009887,0.004100,0.088490,1.530685,3.572005,10.495195,1.002050,33.492569,29.493722,4.132947e+60,0.338688,3.639938,0.910955
std,6.640253,1.446860e+05,0.531518,7292.831848,0.149451,0.418851,0.107631,0.357382,0.468868,0.495026,0.116068,0.29611,0.231400,0.228192,0.083114,0.188855,0.162230,0.246499,0.117895,0.037529,0.045960,0.086916,0.072473,0.037532,0.085819,0.008004,0.160082,0.402855,0.379570,0.190791,0.371855,0.160874,0.386379,0.125518,0.147027,0.136447,0.157591,0.096454,0.112792,0.098736,0.063901,0.283983,0.500099,1.225897,4.732204,0.045232,44.965528,3.245086,5.012466e+62,0.473279,1.158213,0.284819
min,1.000000,1.000003e+07,-18.000000,22.370851,-4.000000,-18.000000,-9.000000,-17.000000,0.000000,0.000000,0.000000,0.00000,-13.000000,-16.000000,-5.000000,-10.000000,-18.000000,-17.000000,-13.000000,-2.000000,-3.000000,-7.000000,-8.000000,-3.000000,-9.000000,-1.000000,-12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.139239e+04,0.000000,1.000000,0.000000
25%,8.000000,1.012481e+07,0.000000,3590.822394,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,6.000000,1.000000,2.000000,30.000000,6.092366e+04,0.000000,3.000000,1.000000
50%,13.000000,1.025000e+07,0.000000,6927.344873,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,3.000000,11.000000,1.000000,3.000000,30.000000,7.955774e+04,0.000000,4.000000,1.000000
75%,19.000000,1.037542e+07,0.000000,10787.338532,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,4.000000,15.000000,1.000000,99.000000,30.000000,1.023826e+05,1.000000,4.000000,1.000000
max,24.000000,1.049999e+07,0.000000,116061.594038,3.000000,6.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.00000,2.000000,2.000000,1.000000,1.000000,0.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,6.000000,28.000000,2.000000,99.000000,35.000000,6.079152e+64,1.000000,9.000000,1.000000

In [5]:
df[df['txn_cnt'] < 0].head()

,dt,chid,shop_tag,txn_cnt,txn_amt,domestic_offline_cnt,domestic_online_cnt,overseas_offline_cnt,overseas_online_cnt,domestic_offline_amt_pct,domestic_online_amt_pct,overseas_offline_amt_pct,overseas_online_amt_pct,card_1_txn_cnt,card_2_txn_cnt,card_3_txn_cnt,card_4_txn_cnt,card_5_txn_cnt,card_6_txn_cnt,card_7_txn_cnt,card_8_txn_cnt,card_9_txn_cnt,card_10_txn_cnt,card_11_txn_cnt,card_12_txn_cnt,card_13_txn_cnt,card_14_txn_cnt,card_other_txn_cnt,card_1_txn_amt_pct,card_2_txn_amt_pct,card_3_txn_amt_pct,card_4_txn_amt_pct,card_5_txn_amt_pct,card_6_txn_amt_pct,card_7_txn_amt_pct,card_8_txn_amt_pct,card_9_txn_amt_pct,card_10_txn_amt_pct,card_11_txn_amt_pct,card_12_txn_amt_pct,card_13_txn_amt_pct,card_14_txn_amt_pct,card_other_txn_amt_pct,masts,educd,trdtp,naty,poscd,cuorg,slam,gender_code,age,primary_card
2134,1,10125723,43,-1,4527.939194,0,-1,0,0,0.00,1.00,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1,3.0,8.0,1,1,30,133000.939458,0.0,4.0,1
15013,1,10282172,10,-1,2963.791957,0,0,0,-1,0.00,0.00,0.0,1.0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,2.0,2.0,1,6,30,78221.469775,1.0,3.0,1
26142,1,10433545,48,-2,7382.464152,-3,1,0,0,0.16,0.84,0.0,0.0,0,0,0,0,0,0,0,0,0,-2,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,3.0,2.0,1,1,30,117920.305695,1.0,5.0,1
32486,1,10017950,6,-1,5027.737383,0,-1,0,0,0.00,1.00,0.0,0.0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,5.0,2.0,1,6,30,75791.337935,0.0,4.0,1
32795,1,10078477,19,-1,8275.363098,0,-1,0,0,0.00,1.00,0.0,0.0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,3.0,11.0,1,3,30,NaN,0.0,4.0,0

In [6]:
df[(df['txn_cnt'] <= 0) & ((df['domestic_offline_cnt'] < 0) | (df['domestic_online_cnt'] < 0) | (df['overseas_offline_cnt'] < 0) | (df['overseas_online_cnt'] < 0))].tail()

,dt,chid,shop_tag,txn_cnt,txn_amt,domestic_offline_cnt,domestic_online_cnt,overseas_offline_cnt,overseas_online_cnt,domestic_offline_amt_pct,domestic_online_amt_pct,overseas_offline_amt_pct,overseas_online_amt_pct,card_1_txn_cnt,card_2_txn_cnt,card_3_txn_cnt,card_4_txn_cnt,card_5_txn_cnt,card_6_txn_cnt,card_7_txn_cnt,card_8_txn_cnt,card_9_txn_cnt,card_10_txn_cnt,card_11_txn_cnt,card_12_txn_cnt,card_13_txn_cnt,card_14_txn_cnt,card_other_txn_cnt,card_1_txn_amt_pct,card_2_txn_amt_pct,card_3_txn_amt_pct,card_4_txn_amt_pct,card_5_txn_amt_pct,card_6_txn_amt_pct,card_7_txn_amt_pct,card_8_txn_amt_pct,card_9_txn_amt_pct,card_10_txn_amt_pct,card_11_txn_amt_pct,card_12_txn_amt_pct,card_13_txn_amt_pct,card_14_txn_amt_pct,card_other_txn_amt_pct,masts,educd,trdtp,naty,poscd,cuorg,slam,gender_code,age,primary_card
6548868,24,10370817,37,-2,5480.168714,-2,0,0,0,1.0,0.0,0.0,0.0,0,0,0,-2,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,3.0,15.0,1,3,30,64803.059052,1.0,3.0,1
6550524,24,10436626,44,-1,11380.568655,0,-1,0,0,0.0,1.0,0.0,0.0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,2.0,12.0,1,1,30,68561.179121,NaN,NaN,1
6552986,24,10109555,19,-2,15602.142458,0,-2,0,0,0.0,1.0,0.0,0.0,0,0,0,0,0,-2,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,6.0,8.0,1,2,30,78221.469775,0.0,2.0,1
6554323,24,10300125,9,-4,14304.881080,0,-4,0,0,0.0,1.0,0.0,0.0,0,0,0,-4,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,3.0,12.0,1,1,30,49961.938964,1.0,4.0,1
6557628,24,10021524,43,-1,8630.883105,0,-1,0,0,0.0,1.0,0.0,0.0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,4.0,17.0,1,2,30,76875.484753,1.0,3.0,1

# 預測說明
+ 預測每位顧客下個月份**消費金額前三名的消費類別排序**。
+ 需預測的消費類別包含16種類，請僅針對這16類進行預測回傳。（請參閱Dataset Download區：需預測的消費類別）。
+ 需預測的顧客即為訓練資料集的所有顧客，顧客名單以及提交欄位產出請參閱Dataset Download區：需預測的顧客名單及提交檔案範例。
+ 請預測結果務必能夠排序出第一至第三名，不接受預測結果含有同名次之狀況。

---
### GroupBy 客戶 與 消費類別

In [7]:
chid_groupby_shop_tag = df.groupby(['chid', 'shop_tag'])

In [8]:
tmp = chid_groupby_shop_tag[['txn_cnt', 'txn_amt']].sum()
cnt_amt_df = tmp.sort_values('txn_cnt', ascending= False).sort_index(level='chid', sort_remaining=False)
cnt_amt_df

                   txn_cnt       txn_amt
chid     shop_tag
10000000 10              5  20563.272653
         45              3  23157.670574
10000001 15              8  38640.961003
         45              3  10401.103280
         48              2   7060.142894
...                    ...           ...
10499998 17              1   8373.156490
         19              1  14659.957396
         37              1  10579.441044
         21              1   8547.302199
10499999 22              1   4219.341890

[3233541 rows x 2 columns]

In [9]:
for idx in cnt_amt_df.index.levels[0][:10]:
    print(cnt_amt_df.loc[idx].index[:3].values)

['10' '45']
['15' '45' '48']
['22']
['22']
['48' '37' '2']
['37' 'other']
['37' '10' '2']
['45']
['36' '44' '15']
['other' '46' '19']

### 按照類別消費金額做排序
---
#### ex. 第25~31天內
+ 類別 A 買了 10 筆共花了 3000
+ 類別 B 買了 3 筆共花了 5000
+ 類別 C 買了 1 筆共花了 150
---
#### Answer : [B A C]

## TODO

predict 16 groups : 2,6,10,12,13,15,18,19,21,22,25,26,36,37,39,48

---
要先有的background:
+ 每個類型的花費大概是多少錢 ? [可能有些類別的金額很發散 有些大概集中在某個小區間內]
+ scoring function
+ 應該要以消費習慣為導向 (先猜常買的種類)
+ txn_cnt 有存在 0 的奇怪現象

待驗證假設 :
+ 49 個shop_tag 可以被視為 16 個 group => shop_tag 和 group 的關係
+ 如果用每月的前N天去預測後K天的前三種類別大多情況可以推敲得出來